### ISSUE TITLE
Is this a good place for eav-map?

### ISSUE THREAD

**Issue by eraserhd** [clyfe/clara-eav#3]
We've put this here, but it really is unrelated to `clara-eql`.  If it works here, I'll make a PR.

https://github.com/eraserhd/clara-eql/blob/develop/src/net/eraserhead/clara_eql/eav_map.clj

**Comment by clyfe** [comment]
No, at least not now. We have mildly similar `er/entity` & `er/entities`.
I'd like to introduce a datascript-style schema (`:db.cardinality/many`) before expanding the API with many-valued semantics.
Thanks for the tip, the project looks interesting.
