### ISSUE TITLE
Magic map like Datomic `d/entity`?

### ISSUE THREAD

**Issue by eraserhd** [clyfe/clara-eav#4]
We would like this as a mechanism to aid in debugging - inspecting the session.  Zach Tellman's Potemkin has a library that allows easier creation of magic maps, and the `eav-map` mentioned in #3 would make it nicely feasible.

So, we are probably going to build this regardless.  Does it belong here?

**Comment by clyfe** [comment]
I'm reluctant to allow reading of data other than via Clara rules/queries; like, say: reading directly from the session. How would the API look exactly? `(clara-eav.tools/entity session eid)`?

**Comment by eraserhd** [comment]
Yes, like that.

Without eav-map or another mechanism to accumulate all the triples in the system, I don’t think this is possible, though.

**Comment by clyfe** [comment]
Many-valued aside, `eav-map` and `er/entities` accumulators are rather similar.
More tooling would be useful, but will hold off adding to the API before a datascript-style schema is implemented.
